# Generated by Django 4.2.3 on 2023-08-10 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('codigo_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo_curso', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termno', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.IntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido_pat', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido_mat', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('codigo_modulo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('duracion_horas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanFormativo',
            fields=[
                ('codigo_plan_formativo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('duracion_horas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plan_formativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('codigo_region', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('codigo_tutor', models.IntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido_pat', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido_mat', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tutor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursoModuloTutor',
            fields=[
                ('codigo_curso', models.OneToOneField(db_column='codigo_curso', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.curso')),
            ],
            options={
                'db_table': 'curso_modulo_tutor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanModulo',
            fields=[
                ('codigo_plan_formativo', models.OneToOneField(db_column='codigo_plan_formativo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.planformativo')),
            ],
            options={
                'db_table': 'plan_modulo',
                'managed': False,
            },
        ),
    ]
